"""
Cross-validation: compare PyTorch SINDy outputs against MATLAB reference data.

The files in tests/matlab_reference are generated by the original MATLAB
implementation via sparsedynamics/export_for_verification.m. This script does
not require MATLAB at test time; it compares PyTorch results with those saved
MATLAB .mat fixtures.

Tests:
  1. PolynomialLibrary Theta matrix (2-var and 3-var, multiple poly orders)
  2. STLS coefficient matrix on synthetic problem
  3. Linear2D full pipeline
  4. Lorenz full pipeline (noiseless)
"""

from pathlib import Path
import sys

import numpy as np
from scipy.io import loadmat
import torch

import sindy_torch


REF_DIR = Path(__file__).resolve().parent / "matlab_reference"
REQUIRED_FIXTURES = [
    "pooldata_test.mat",
    "pooldata_test3.mat",
    "sparse_small.mat",
    "linear2d.mat",
    "lorenz.mat",
]

PASS_COUNT = 0
FAIL_COUNT = 0


def require_fixtures():
    missing = [name for name in REQUIRED_FIXTURES if not (REF_DIR / name).exists()]
    if missing:
        missing_list = ", ".join(missing)
        raise FileNotFoundError(
            f"Missing MATLAB reference fixture(s): {missing_list}. "
            "Regenerate them with the MATLAB command documented in README.md."
        )


def check(name, condition, detail=""):
    global PASS_COUNT, FAIL_COUNT
    if condition:
        PASS_COUNT += 1
        print(f"  PASS: {name}")
    else:
        FAIL_COUNT += 1
        print(f"  FAIL: {name}  {detail}")


def test_pool_data_2var():
    print("\n=== Test 1: PolynomialLibrary (2 variables) ===")
    d = loadmat(REF_DIR / "pooldata_test.mat")
    x_np = d["x_test"]  # (3, 2)
    x_t = torch.tensor(x_np, dtype=torch.float64)

    for po, key in [(2, "Theta_test_p2"), (3, "Theta_test_p3"), (5, "Theta_test_p5")]:
        theta_matlab = d[key]
        lib = sindy_torch.PolynomialLibrary(2, po)
        theta_torch = lib(x_t).numpy()

        check(
            f"shape (polyorder={po})",
            theta_torch.shape == theta_matlab.shape,
            f"PyTorch {theta_torch.shape} vs MATLAB {theta_matlab.shape}",
        )
        if theta_torch.shape == theta_matlab.shape:
            max_err = np.max(np.abs(theta_torch - theta_matlab))
            check(
                f"values (polyorder={po})",
                max_err < 1e-12,
                f"max error = {max_err:.2e}",
            )


def test_pool_data_3var():
    print("\n=== Test 2: PolynomialLibrary (3 variables) ===")
    d = loadmat(REF_DIR / "pooldata_test3.mat")
    x_np = d["x_test3"]
    x_t = torch.tensor(x_np, dtype=torch.float64)
    theta_matlab = d["Theta_test3_p3"]
    lib = sindy_torch.PolynomialLibrary(3, 3)
    theta_torch = lib(x_t).numpy()

    check(
        "shape (3var, polyorder=3)",
        theta_torch.shape == theta_matlab.shape,
        f"PyTorch {theta_torch.shape} vs MATLAB {theta_matlab.shape}",
    )
    if theta_torch.shape == theta_matlab.shape:
        max_err = np.max(np.abs(theta_torch - theta_matlab))
        check(
            "values (3var, polyorder=3)",
            max_err < 1e-12,
            f"max error = {max_err:.2e}",
        )


def test_stls_synthetic():
    print("\n=== Test 3: STLS (synthetic problem) ===")
    d = loadmat(REF_DIR / "sparse_small.mat")
    theta = torch.tensor(d["Theta_small"], dtype=torch.float64)
    dx = torch.tensor(d["dx_small"], dtype=torch.float64)
    xi_matlab = d["Xi_small"]

    xi_torch = sindy_torch.stls(theta, dx, lam=0.1).numpy()

    sp_ml = xi_matlab != 0
    sp_pt = np.abs(xi_torch) > 1e-12
    check(
        "sparsity pattern",
        np.array_equal(sp_ml, sp_pt),
        f"MATLAB nnz={sp_ml.sum()}, PyTorch nnz={sp_pt.sum()}",
    )

    max_err = np.max(np.abs(xi_torch - xi_matlab))
    check("coefficient values", max_err < 1e-3, f"max error = {max_err:.2e}")

    print("    Nonzero entries:")
    for i in range(xi_torch.shape[0]):
        for j in range(xi_torch.shape[1]):
            if abs(xi_torch[i, j]) > 1e-10 or abs(xi_matlab[i, j]) > 1e-10:
                print(
                    f"      [{i},{j}]: "
                    f"PyTorch={xi_torch[i,j]:+.6f}  MATLAB={xi_matlab[i,j]:+.6f}"
                )


def test_linear2d():
    print("\n=== Test 4: Linear 2D full pipeline ===")
    d = loadmat(REF_DIR / "linear2d.mat")
    x = torch.tensor(d["x"], dtype=torch.float64)
    dx_true = torch.tensor(d["dx_true"], dtype=torch.float64)
    dx_noisy = torch.tensor(d["dx"], dtype=torch.float64)
    theta_matlab = d["Theta"]
    xi_matlab = d["Xi"]
    polyorder = int(d["polyorder"].item())
    lam = float(d["lambda"].item())
    n = int(d["n"].item())

    lib = sindy_torch.PolynomialLibrary(n, polyorder)
    theta_torch = lib(x).numpy()
    check("Theta shape", theta_torch.shape == theta_matlab.shape)
    if theta_torch.shape == theta_matlab.shape:
        max_err = np.max(np.abs(theta_torch - theta_matlab))
        check("Theta values", max_err < 1e-10, f"max err={max_err:.2e}")

    xi_noiseless = sindy_torch.stls(
        torch.tensor(theta_torch, dtype=torch.float64),
        dx_true,
        lam=lam,
    ).numpy()
    check("noiseless: x coeff (col 0)", abs(xi_noiseless[1, 0] - (-0.1)) < 0.001)
    check("noiseless: y coeff (col 0)", abs(xi_noiseless[2, 0] - 2.0) < 0.001)
    check("noiseless: x coeff (col 1)", abs(xi_noiseless[1, 1] - (-2.0)) < 0.001)
    check("noiseless: y coeff (col 1)", abs(xi_noiseless[2, 1] - (-0.1)) < 0.001)

    xi_noisy = sindy_torch.stls(
        torch.tensor(theta_torch, dtype=torch.float64),
        dx_noisy,
        lam=lam,
    ).numpy()
    sp_py = np.abs(xi_noisy) > 1e-10
    sp_ml = np.abs(xi_matlab) > 1e-10
    check("noisy: sparsity pattern", np.array_equal(sp_py, sp_ml))
    max_err = np.max(np.abs(xi_noisy - xi_matlab))
    check("noisy: Xi values match MATLAB", max_err < 1e-3, f"max err={max_err:.2e}")

    print("\n    Noisy Xi comparison:")
    for i in range(xi_noisy.shape[0]):
        for j in range(xi_noisy.shape[1]):
            if abs(xi_noisy[i, j]) > 1e-10 or abs(xi_matlab[i, j]) > 1e-10:
                print(
                    f"      [{i},{j}]: "
                    f"PyTorch={xi_noisy[i,j]:+.6f}  MATLAB={xi_matlab[i,j]:+.6f}"
                )


def test_lorenz():
    print("\n=== Test 5: Lorenz full pipeline (noiseless) ===")
    d = loadmat(REF_DIR / "lorenz.mat")
    x_lor = torch.tensor(d["x_lor"], dtype=torch.float64)
    dx_lor = torch.tensor(d["dx_lor"], dtype=torch.float64)
    theta_matlab = d["Theta_lor"]
    xi_matlab = d["Xi_lor"]
    polyorder = int(d["polyorder_lor"].item())
    lam = float(d["lambda_lor"].item())
    n = 3

    lib = sindy_torch.PolynomialLibrary(n, polyorder)
    theta_torch = lib(x_lor).numpy()
    check("Theta shape", theta_torch.shape == theta_matlab.shape)

    if theta_torch.shape == theta_matlab.shape:
        rel_err = np.max(np.abs(theta_torch - theta_matlab)) / (
            np.max(np.abs(theta_matlab)) + 1e-15
        )
        check("Theta values (relative)", rel_err < 1e-10, f"rel err={rel_err:.2e}")

    xi_torch = sindy_torch.stls(
        torch.tensor(theta_torch, dtype=torch.float64),
        dx_lor,
        lam=lam,
    ).numpy()

    sp_py = np.abs(xi_torch) > 1e-10
    sp_ml = np.abs(xi_matlab) > 1e-10
    check(
        "sparsity pattern",
        np.array_equal(sp_py, sp_ml),
        f"PyTorch nnz={sp_py.sum()}, MATLAB nnz={sp_ml.sum()}",
    )

    max_err = np.max(np.abs(xi_torch - xi_matlab))
    check("Xi values", max_err < 1e-3, f"max err={max_err:.2e}")

    sigma, beta, rho = 10.0, 8.0 / 3.0, 28.0
    check("sigma (x in dx/dt)", abs(xi_torch[1, 0] - (-sigma)) < 0.01)
    check("sigma (y in dx/dt)", abs(xi_torch[2, 0] - sigma) < 0.01)
    check("rho (x in dy/dt)", abs(xi_torch[1, 1] - rho) < 0.01)
    check("beta (z in dz/dt)", abs(xi_torch[3, 2] - (-beta)) < 0.01)

    print("\n    Lorenz Xi (nonzero):")
    labels = lib.get_labels(["x", "y", "z"])
    for i in range(xi_torch.shape[0]):
        for j in range(xi_torch.shape[1]):
            if abs(xi_torch[i, j]) > 1e-10 or abs(xi_matlab[i, j]) > 1e-10:
                print(
                    f"      {labels[i]:>8s} [{i},{j}]: "
                    f"PyTorch={xi_torch[i,j]:+12.6f}  "
                    f"MATLAB={xi_matlab[i,j]:+12.6f}"
                )


def main():
    require_fixtures()
    test_pool_data_2var()
    test_pool_data_3var()
    test_stls_synthetic()
    test_linear2d()
    test_lorenz()

    print(f"\n{'=' * 50}")
    print(f"RESULTS: {PASS_COUNT} passed, {FAIL_COUNT} failed")
    if FAIL_COUNT == 0:
        print("All MATLAB fixture verifications PASSED.")
    else:
        print("Some MATLAB fixture verifications FAILED; see above.")
    print(f"{'=' * 50}")
    return FAIL_COUNT == 0


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
